<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>HOME</title>
		<style>
			/* Generated by Font Squirrel (http://www.fontsquirrel.com) on December 15, 2015 */
			/*http://www.fontsquirrel.com/tools/webfont-generator*/
			@font-face {
			    font-family: 'noticia_textregular';
			    src: url('fonts/noticia-text/noticiatext-regular-webfont.eot');
			    src: url('fonts/noticia-text/noticiatext-regular-webfont.eot?#iefix') format('embedded-opentype'),
			         url('fonts/noticia-text/noticiatext-regular-webfont.woff2') format('woff2'),
			         url('fonts/noticia-text/noticiatext-regular-webfont.woff') format('woff'),
			         url('fonts/noticia-text/noticiatext-regular-webfont.ttf') format('truetype'),
			         url('fonts/noticia-text/noticiatext-regular-webfont.svg#noticia_textregular') format('svg');
			    font-weight: normal;
			    font-style: normal;

			}
			/* Generated by Font Squirrel (http://www.fontsquirrel.com) on December 15, 2015 */
			@font-face {
			    font-family: 'oswaldregular';
			    src: url('fonts/oswald/oswald-regular-webfont.eot');
			    src: url('fonts/oswald/oswald-regular-webfont.eot?#iefix') format('embedded-opentype'),
			         url('fonts/oswald/oswald-regular-webfont.woff2') format('woff2'),
			         url('fonts/oswald/oswald-regular-webfont.woff') format('woff'),
			         url('fonts/oswald/oswald-regular-webfont.ttf') format('truetype'),
			         url('fonts/oswald/oswald-regular-webfont.svg#oswaldregular') format('svg');
			    font-weight: normal;
			    font-style: normal;

			}
			body{
				margin: 0 auto;
			}
			header{
				margin: .5em .5em 0 .5em;
				/*width: 99%;*/
				min-height: 150px;
				background-color: #483E3D;
			}
			img#logo{
				position: relative;
				margin-top: 2em;
				margin-left: 1em;
			}
			ul.log{
				position: relative;
				margin-left: 60%;
				margin-top: -2em;
			}
			.log la{
				display: inline-block;
				padding: 1px 10px;
				font-family: 'Noticia Text', serif;
				font-size: 18px;
				color: white;
			}
			.nav{
				position: relative;
				margin-left: 35%;
				margin-top: 1em;
				margin-bottom: 0em;
				color: white;
			}
			img#menu{
				display: none;
			}
			ul.nav la{
				/*display: inline-block;*/
				padding: 1px 10px;
				font-family: 'Oswald', sans-serif;
				font-size: 29px;
			}
			aside{
				background-color: #625452;
				width: 25%;
				min-height: 40em;
				margin-left: .5em;

			}
			footer{
				background-color: #483E3D;
				margin: 0em 0.5em 0em 0.5em;
			}
			footer div{
				margin-left: 1%;
				float: left;
				width: 32.3%;
				font-family: 'Noticia Text', serif;
				font-size: 18px;
				color: white;
			}
			footer span{
				margin: 0 auto;
				color: white;
			}
			@media screen and (max-width: 800px) {
				footer{
					margin: .5em .5em 0 .5em;
				}
				footer div{
					width: 99%;
					font-family: 'Noticia Text', serif;
					font-size: 38px;
					color: white;
					text-align: center;
				}
				footer span{
					margin: 0 auto;
					color: white;
					font-family: 'Noticia Text', serif;
					font-size: 18px;
					text-align: center;
				}
				footer span{
					margin: 0 auto;
					color: white;
				}
				
				aside{
					/*display:none;*/
					min-height: 400px;
				}
				img#menu{
					display: block;
					width: 30px;
					height: 30px;
				}
				img#menu:hover, ul.nav la{
					background-color: red;
					display: block;
				}
				img#logo{
					width: 90%;
					margin: 1em;
				}
				ul.nav la{
					display: none;
				}
				ul.log{
					position: relative;
					margin-left: 1.5em;
					margin-top: 2em;
					margin: 0 auto;
					text-align: center;
				}
				.log la{
					display: block;
					padding: 1px 10px;
					font-family: 'Noticia Text', serif;
					font-size: 50px;
					color: white;
				}

			}
		</style>
	</head>
	<body>
		<header>
			<img id="logo" src="imagenes/logo.png" alt="logo">
			<nav >
				<ul class="log">
					<la>Login</la>
					<la>Registrate</la>
					<la>Idioma</la>
				</ul>
			</nav>
			<nav>
				<img id="menu" src="./imagenes/menu.png" alt="menu">
				<ul class="nav">
					<la>Patines</la>
					<la>Accesorios</la>
					<la>Marca</la>
					<la>Ofertas</la>
					<la>Personaliza</la>
				</ul>
			</nav>
		</header>

		<aside>
		</aside>
		<section>
			<article>
			</article>
		</section>
		<footer>
			<div>
				<p>
				¿Necesitas ayuda?<br>
				Localizar o gestionar compras<br>
				Tarifas y políticas de envío<br>
				Devolver o reemplazar productos<br>
				</p>
			</div>
			<div>
				<p>
				Métodos de pago TTOUNKYO<br>
				Métodos de pago<br>
				Conversor de divisas<br>
				Cheques Regalo<br>
				</p>
			</div>
			<div>
				<p>
				Avisos y condiciones<br>
				Condiciones de Uso y Venta<br>
				Aviso de privacidad<br>
				Área legalCookies y Publicidad
				en Internet<br>
				</p>
			</div>
			<span>
				© 1996-2015, ttounkyo.com, Inc. o afiliados. Todos los derechos reservados.
			</span>
		</footer>
	</body>
</html>